#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.incremental=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true

#Gradle Optimizations
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android Build & Performance Optimizations
android.nonTransitiveRClass=true
android.useAndroidX=true
android.enableR8.fullMode=true
android.enableAapt2Worker=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
