#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.incremental=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true

#Gradle Optimizations
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.configuration-cache=true
org.gradle.caching=true

#Desktop-only build toggle (Set to true to skip Android/Web/iOS targets & modules for fast desktop development)
flint.desktopOnly=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true